admin:
  existingSecret: grafana-secrets
service:
  type: ClusterIP
downloadDashboardsImage:
  repository: dciangot/curl
  tag: latest
  sha: ""
  pullPolicy: IfNotPresent
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.prometheus.svc
      access: proxy
      isDefault: true
dashboards:
  default:
    prometheus-stats:
      gnetId: 10000
      revision: 1
      datasource: Prometheus
    kube-eagle-stats:
      gnetId: 9871
      revision: 2
      datasource: Prometheus
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards
ingress:
  ingressClassName: nginx
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: {{ cluster_issuer_name }}
  hosts:
  - "grafana.{{ dns_name }}"
  tls:
  - hosts:
    - "grafana.{{ dns_name }}"
    secretName: grafana-secret
grafana.ini:
  security:
    cookie_secure: true
  database:
    wal: true
